import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [borrower, setBorrower] = useState("");
  const [amount, setAmount] = useState("");

  const handleCreateLoanSubmit = async () => {
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>XRPLendNet</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <div className="mt-10">
          <p className="mt-5 text-black dark:text-white">
            Create a loan
          </p>
          <div className="flex flex-wrap gap-5">
            <input
              value={borrower}
              onChange={(e) => setBorrower(e.target.value)}
              type="text"
              placeholder="Enter borrower address (0x...)"
              className="rounded-full border border-stroke px-6 py-2.5 shadow-solid-2 focus:border-primary focus:outline-none dark:border-strokedark dark:bg-black dark:shadow-none dark:focus:border-primary"
            />
            <input
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              type="text"
              placeholder="Enter loan value in XRP"
              className="rounded-full border border-stroke px-6 py-2.5 shadow-solid-2 focus:border-primary focus:outline-none dark:border-strokedark dark:bg-black dark:shadow-none dark:focus:border-primary"
            />
            <button
              onClick={handleCreateLoanSubmit}
              aria-label="button"
              className="flex rounded-full bg-black px-7.5 py-2.5 text-white duration-300 ease-in-out hover:bg-blackho dark:bg-btndark dark:hover:bg-blackho"
            >
              Submit
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
